name: Automated Testing

on: push

jobs:
  unit-testing: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run unit tests
        run: |
          python -m pytest --cov=src --cov-report=xml --cov-report=html --cov-report=term-missing --cov-fail-under=100 --junitxml=junit/test-results.xml