name: Automated Testing

on: push

jobs:
  unit-testing: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
      - name: Install dependencies
        run: pip install pytest
      - name: Run tests
        run: pytest test.py
